### ISSUE TITLE
clean up to the right .dll project structure

### ISSUE THREAD

**Issue by ponyatov** [qwertyuiop3/Segregation#1]
https://profi.ru/backoffice/n.php?o=47834041

I'm surprised with a very strange decision about the code structuring. As a variant, I can try to restructure it and build some cross-compilation scripts (Linux host, Docker maybe for repeatability), but I need some manuals and samples about this library usage -- tests must be written on every part goes under the change.

**Comment by ponyatov** [comment]
I see some binary data and code that does something in .hpp files -- why?

Anybody who writes in C knows that it should be splitted for inceremental build -- .cpp for code, and .hpp only for types, function declarations, and maybe macroses.

**Comment by qwertyuiop3** [comment]
there is no strong defined coding standards you make your own choice what standards you're going to follow also "header-only" isn't uncommon practice

didn't you noticed multi-processor compilation is disabled? i don't know how you found this project but it's not used as you think after all it doesn't really matters how long it takes to compile five or ten seconds only thing that matters is how it will perform in the end

talking about coding style in order to optimize code generation i would try to get rid of bad habits instead of pointless compilation time optimization

for example https://github.com/qwertyuiop3/Segregation/blob/6bb0f4f5226e8919c9a191a64fed219a91b7dd2b/Converge_Angles.hpp#L52

most compilers compile static as or even worse with safety checks
```
if (!(global.flag & 1)){
global.flag |= 1;
global.value = init();
}
anything(global.value);
```
so it doubles or triples global memory access depending on what is stored inside
there is faster way to check for initialization but unfortunately i can't tell compiler to do so
