### ISSUE TITLE
autowall

### ISSUE THREAD

**Issue by Zuzie-isHere** [qwertyuiop3/Segregation#13]
This is the last request I'm asking for now. Where can I create an autowall code? I won't use it for boosting, honestly. It's mainly because I want to attempt to create a bypass for the k1ngston block, and people usually use autowall for that. I don't want to get killed for not having it

Edit:Thanks in advance, and yes, I know it's a lot for someone who is just starting to learn, but I'll try to do it because I want to challenge myself. I don't know; I hope everything goes well.

**Comment by qwertyuiop3** [comment]
>Where can I create an autowall code?

https://github.com/qwertyuiop3/Segregation/blob/3fdc1a5f85341c6b42b5c917cb11be3778aae0bf/Copy_Command.hpp#L440

autowall is basically [this](https://github.com/VSES/SourceEngine2007/blob/master/se2007/game/shared/cstrike/cs_player_shared.cpp#L312) function rebuilt without few unnecessary things like spread calculation, any kind of visualization and damage registration

not much to say about implementation either have sdk (2006 is most close to v34) connected or have advanced reverse engineering knowledge to build your own

there is also alternative way without rebuilding (l4d2 as example):
- set weapon_data->m_nBullets to 1 so trace is performed only once with shotguns
- null audio device so game doesn't plays any sounds
- disable tracers
- disable impacts (there are multiple variables in l4d2 for that)
- call FX_FireBullets
- as soon as your mid-function hook gets triggered:
preserve registers (situatively with eflags and fpu)
supply stack address (usually esp register) according to your worker function's calling convention
call worker function
grab tracer from stack (usually locally allocated)
do your stuff (comparison, damage calculation)
as soon as you exit worker function restore registers and continue execution
- restore everything

or just paste it from insomnia since you're trying to mimic it: [oldcsshook.zip](https://github.com/qwertyuiop3/Segregation/files/14037483/oldcsshook.zip)
