### ISSUE TITLE
"enemy check", grenades, defusing, glow, lagcompensation

### ISSUE THREAD

**Issue by Zuzie-isHere** [qwertyuiop3/Segregation#14]
Hello, I apologize for the inconvenience, but I've been attempting to deactivate the enemy check feature without success as it consistently crashes. Could you please provide guidance on how to deactivate it while ensuring it remains accessible via console commands rather than simply deleting it? Additionally, I'm encountering an issue where I'm unable to throw grenades. Could you advise on how to resolve this? Furthermore, I'm interested in implementing a feature where holding down the 'E' key turn off the Antiaim, 
and I'd also like to incorporate a glow effect. Lastly, I've observed that the recommendation you provided for my high ping seems to exacerbate aimbot miss, even with brute force disabled against bots
Additionally, a friend suggested that adjusting the lag comp could improve my experience with my current ping. I would appreciate any suggestions or guidance on how to make this adjustment effectively.

RU(maybe there are some words wrong but I think it could be easier for you):
Привет, прошу прощения за неудобства, но я не смог отключить функцию проверки противника без успеха, так как она постоянно вылетает. Не могли бы вы подсказать, как отключить её, гарантируя доступность через консольные команды, а не просто удаляя её? Кроме того, у меня возникла проблема с невозможностью бросить гранаты. Могли бы вы посоветовать, как это исправить? Кроме того, меня интересует реализация функции, при удерживании клавиши 'E', чтобы отключалась Антиайм, и я также хотел бы внедрить эффект свечения. Наконец, я заметил, что рекомендация, которую вы дали для моего высокого пинга, кажется усиливает промахи при использовании aimbot, даже если brute force отключен против ботов. Кроме того, друг посоветовал, что изменение компенсации задержки может улучшить мой опыт при моём текущем пинге. Буду благодарен за любые предложения или рекомендации о том, как сделать эту настройку эффективно.

**Comment by qwertyuiop3** [comment]
> I've been attempting to deactivate the enemy check feature without success as it consistently crashes.
 
there is no "enemy check" at **targets** is designed that way.

> Could you please provide guidance on how to deactivate it while ensuring it remains accessible via console commands rather than simply deleting it?

add "else" condition here
https://github.com/qwertyuiop3/Segregation/blob/7f1b81e2262260a0063631f4a4f778c404a33b80/Copy_Command.hpp#L824
inside "else" condition do exact same thing but using your angle as basis
```
if (Interface_Enemy_Check.Integer == 0) //"remains accessible via console commands"
{
	  if (Send_Packet == 0)
  	  {
	 	  if ((Command->Command_Number % 2) == 0)
	  	  {
		  	  Command->Angles[1] += Interface_First_Choked_Angle_Y.Floating_Point;
	  	  }
	  	  else
	  	  {
		  	  Command->Angles[1] += Interface_Second_Choked_Angle_Y.Floating_Point;
	  	  }
  	  }
  	  else
  	  {
	 	   Command->Angles[1] += Interface_Angle_Y.Floating_Point;
 	  }
}
```

> Additionally, I'm encountering an issue where I'm unable to throw grenades.

not much to say about optimal solution (my hdd is currently dead to take look) but easiest would be just checking if virtual table of weapon you're holding doesn't equals C_HEGrenade
```
if (*(void**)Weapon != 607415876)
{
	  ...
}
```

> Furthermore, I'm interested in implementing a feature where holding down the 'E' key turn off the Antiaim.

add that condition above of all things you don't want to be activated when holding +use
```
if ((Command->Buttons & 32) == 0)
{
	  ...
}
```

> I'd also like to incorporate a glow effect.

that's probably what most of people are using:
https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/game/client/glow_outline_effect.cpp
but you can also take look at few more possible realizations:
https://developer.download.nvidia.com/SDK/9.5/Samples/3dgraphics_samples.html#Glow
https://developer.download.nvidia.com/SDK/9.5/Samples/3dgraphics_effects.html#post_halo

can't help anymore. it's out of my interest

> I've observed that the recommendation you provided for my high ping seems to exacerbate aimbot miss, even with brute force disabled against bots

nocebo (it's unrelated in any way to aimbotting but to synchronization of bruteforce)

> Additionally, a friend suggested that adjusting the lag comp could improve my experience with my current ping.

fakelagging players aren't lagcompensated on high velocity (√(4096) units) there is nothing to adjust lagcompensation related but to extrapolate

fakelagging players are lagcompensated on low velocity and taking into account your high ping server will additionally apply interpolation (unless exact time given): https://github.com/VSES/SourceEngine2007/blob/master/se2007/game/server/player_lagcompensation.cpp#L460

all these "Lerp(x, y)" (linear interpolation) calls that are done above aren't implemented in seg because of guessing it involves to determine how simulation time you've received is far away from server

i'd guess hardcoding these in your case would be rational solution as they're valid most of time (?)

**edit**

managed to recall debugging from years ago. my last words seem to be unlikely

**Comment by Zuzie-isHere** [comment]
Thank you very much for everything I really appreciate it again sorry for bothering you

RU:
Спасибо большое за всё, я очень ценю это. Ещё раз извините за беспокойство.
