### ISSUE TITLE
high ping

### ISSUE THREAD

**Issue by Zuzie-isHere** [qwertyuiop3/Segregation#8]
Hello, I understand that this is not a problem per se, but I would appreciate it if you could correct it or provide a solution. Segregation is a very effective cheat for playing boosted hvh. However, due to my high ping (280), I am unable to play properly, as it shoots as if it had accuracy hit. Thank you.

**Comment by qwertyuiop3** [comment]
to remove delay replace (in Copy_Command.hpp)
```
if (__builtin_fabsf(Global_Variables->Current_Time - Shot_Time) > 0.5f)
{
	if (Shot_Time == 0)
	{
```
with
```
if (1)
{
	if (1)
	{
```
now either remove all "Add_Listener" calls (this will invalidate bruteforce memory) or go to Copy_Command.hpp and replace
```
if (Interface_Bruteforce.Integer == 1)
```
with
```
if (Interface_Bruteforce.Integer == 1 && (Shot_Time == 0 || __builtin_fabsf(Global_Variables->Current_Time - Shot_Time) > 0.5f))
```
taking your ping into account 0.5f may be replaced with some greater value like 0.5f * 2

optimal solution would look slightly different (disabling bruteforce individually instead of disabling completely) but i can't provide code for it right now and personally i would go with first solution that invalidates bruteforce memory it will serve better in most of situations

regarding inaccuracy with high ping there is only one solution (movement simulation) and that's unreliable because of few reasons:
- server doesn't provides input data required for acceleration of other players (m_flStamina to be exact)
- predicting even straight line acceleration would require you to know exact logic of your opponent's strafes
- predicting input (e.g. duck/jump) is impossible and one mispredicted input in midway of simulation is fatal

so obviously it's mostly guessing and implementing it in publicly available branch would just nullify efficiency of it

**Comment by Zuzie-isHere** [comment]
Hello, thank you very much, I really appreciate it, solved the problem regarding the shooting, however the game crashed once when I was playing on a server I wanted to go try it on a local server and when using the command map aim_at_texture2 it crashed I tried joining a local server and there are no problems and then I tried to access another internet server after that and there are no problems either. I suppose it could be that a crash occurs when changing the map. I would like it if you could take a look at it. If it is just a wrong assumption, let me know. I apologize to you and I thank you even more for responding to my problems repeatedly <3 I would also like it if possible if you could remind me where the autostraffe is in segregation :P

**Comment by qwertyuiop3** [comment]
> the game crashed once when I was playing on a server I wanted to go try it on a local server and when using the command map aim_at_texture2 it crashed

it's unrelated to segregation in any way

to be exact there are multiple bugs (at least three i had experienced myself) in this version of engine:

---
- crash on server restart is explained by fact that global/static variables are zero-initialized on startup (so it doesn't happens for first time) but afterwards on server shutdown variables aren't zero-reinitialized so what we have in end client/server attemps to do some kind of action during initialization that shouldn't be done unless server is fully initialized thus causing crash

personally i never looked into exact reason (variable) causing crash as it doesn't causes any discomfort for me

- crash on map loading or during gameplay (usually on modded servers) is explained by CMaterialSystem::Bind function that attemps to bind invalid material

fortunately i had it fixed back in days (so just tell me if you need it i'll take look where i had saved fix for it)

- crash on player setting **malicious** spray thus enforcing client to create invalid texture and crash

workaround to this would be setting r_decals to 0

---
next time when crash happens and you want to know exact reason send me latest *.mdmp file from game folder

> where the autostrafe is in segregation

[here](https://github.com/qwertyuiop3/Segregation/blob/ba090450e15c9574917094c1ffd1446799dd8d8e/Copy_Command.hpp#L54-L79)

**Comment by Zuzie-isHere** [comment]
thank you <3 if I have any errors again about this I will send you the .mdp file Thank you again for everything and for having so much patience with me <3
